spring:
  application:
    name: post-service

server:
  port: ${PORT:8001}

logging.pattern.level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

comment-service:
  base-url: http://localhost:8002